baseurl = "https://www.bad-stats.com"
title = "Bad Statistics"
author = "Daniel Gilbert"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Bad Statistics"

[[menu.main]]
    name = "Home"
    url = "https://bad-stats.com"
    weight = 1
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 2
